# Generated by Django 5.2.7 on 2025-12-29 18:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_expediente', models.TimeField(default='09:00')),
                ('hora_fim_expediente', models.TimeField(default='18:00')),
                ('almoco_inicio', models.TimeField(default='12:00')),
                ('almoco_fim', models.TimeField(default='13:00')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=10, help_text='Tempo extra entre serviços')),
            ],
            options={
                'verbose_name_plural': 'Configurações de Horário',
            },
        ),
        migrations.CreateModel(
            name='DiaFechado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dias Fechados',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao_minutos', models.PositiveIntegerField(help_text='Duração em minutos (ex: 30, 60, 90)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('senha', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('dia_semana', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField()),
                ('senha', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando'), ('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='clientes.cliente')),
                ('servicos', models.ManyToManyField(blank=True, related_name='agendamentos', to='agendamentos.servico')),
            ],
            options={
                'ordering': ['data', 'hora'],
                'unique_together': {('data', 'hora')},
            },
        ),
    ]
