# Generated by Django 5.2.7 on 2026-01-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('clientes', '0002_rename_whatsapp_cliente_telefone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='configuracaohorario',
            name='tolerancia_minutos',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='senha',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariofixo',
            name='senha',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
