# Generated by Django 5.2.7 on 2026-01-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='whatsapp',
            new_name='telefone',
        ),
    ]
